#!/bin/sh

status="$(dunstctl is-paused)"

if [ "$status" = "false" ]; then
		dunstctl set-paused true
		echo "Do not disturb OFF" | dmenu
elif [ "$status" = "true" ]; then
		dunstctl set-paused false
		echo "Do not disturb ON" | dmenu
fi
