#!/bin/sh

# To script works as root
xhost +SI:localuser:root

xrandr --output eDP-1 --mode 1920x1080 --pos 320x1080 --rotate normal --output HDMI-1 --primary --mode 2560x1080 --rate 100 --dpi 103 --scale 1x1 --pos 0x0 --rotate normal

setxkbmap -layout us -variant dvorak-intl && setxkbmap -option caps:escape

for i in $(seq 1 5)
do
		xdotool key super+period && xdotool key super+$i && xdotool key super+period && xdotool key super+$i key shift+super+period
done


ISROOT=$(id -u)

if [ "$ISROOT" = 0 ] ; then
	cd /home/frank/.config/dwm/ultra-wide-dwm/ && make clean install
	xdotool key shift+super+q
fi
