#!/bin/sh
xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --primary --mode 2560x1080 --pos 1920x0 --rotate normal

setxkbmap -layout us -variant dvorak-intl && setxkbmap -option caps:escape

for i in $(seq 1 5)
do
		xdotool key super+period && xdotool key super+$i && xdotool key super+period && xdotool key super+$i key shift+super+period
done

cd /home/frank/.config/dwm/ultra-wide-dwm/ && make clean install

xdotool key shift+super+q
