#!/bin/sh

setxkbmap -layout us,us -variant ,dvorak -option "lv3:rwin_switch,grp:alt_space_toggle"
# setxkbmap -layout us,us -variant ,dvorak-intl -option "lv3:rwin_switch,grp:alt_space_toggle"
# change esc with caps lock
setxkbmap -option caps:escape
