#!/bin/sh
BROWSER=$1
APP_LINK="https://gemini.google.com/app"
WINDOW_NAME="gemini"

case "$BROWSER" in
	brave) brave --profile-directory="Profile 3" --window-name=$WINDOW_NAME --app=$APP_LINK ;;
	thorium) thorium-browser --window-name=$WINDOW_NAME --app=$APP_LINK ;;
	chromium) chromium --profile-directory="Default" --window-name=$WINDOW_NAME --app=$APP_LINK ;;
	*) chromium --profile-directory="Default" --window-name=$WINDOW_NAME --app=$APP_LINK ;;
esac
