#!/bin/sh

# Remove package manager cache
yay --noconfirm --needed -Sc && 

# Empty trash
trash-empty -f && 

# Removed unused dependecies
pacman -Rsn --noconfirm $(pacman -Qdtq)  &&

# Remove python cache
pip cache purge &&

# Clean docker
docker image prune -a

# Ask to start bleachbit
"$HOME"/.scripts/prompt.sh "Start bleachbit?" bleachbit

# Ask to start baobab
"$HOME"/.scripts/prompt.sh "Start baobab?" baobab

printf "\n AVISO: Não esqueça de elimnar snapshots antigos do timeshift!!!\n"
printf "Se precisar de mais espaço rode o código abaixo nos repositórios \n git reflog expire --all --expire=now \n git gc --prune=now --aggressive"
