#!/bin/sh

# To script works as root
xhost +SI:localuser:root

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --off

setxkbmap -layout us -variant dvorak-intl && setxkbmap -option caps:escape

for i in $(seq 1 9)
do
		xdotool key super+period && xdotool key super+$i && xdotool key super+period && xdotool key super+$i key shift+super+period
done

ISROOT=$(id -u)

if [ "$ISROOT" = 0 ] ; then
	cd /home/frank/.config/dwm/laptop-dwm/ && make clean install
	xdotool key shift+super+q
fi ;

cdwm laptop ;

dwmblocks
