#!/bin/sh

/usr/bin/dash $HOME/.scripts/pessoal-tmux &
# obsidian &
anki &
spotify &
qutebrowser &
# /usr/bin/dash $HOME/.scripts/brave-pessoal &
whatsapp-nativefier &
portmaster &
rm $HOME/Downloads

bluetoothctl connect CC:98:8B:C1:5C:78; kill -46 $(pidof dwmblocks)
