#!/bin/sh

/usr/bin/dash $HOME/.scripts/web-pessoal &
/usr/bin/dash $HOME/.scripts/pessoal-tmux &
/usr/bin/bash $HOME/.scripts/configure-trackball.sh &
/usr/bin/calibre &
kill-xautolock.sh &
rm $HOME/Downloads &

#################
# DISABLED
#################
# portmaster &
# obsidian &
# anki &
# spotify-launcher &
