#!/bin/sh

ip=$(cat "$HOME"/.scripts/.env/ip-proxmox-server)
active=$(ping -c 1 "$ip" | grep -Po "[0-9]+(?=%)" )

shutdown_server() {
	notify-send  "Server" "Shuting down server"
	echo "Shuting down server"
	ssh proxmox "shutdown now"
}

check_server_shutdown() {
	while [ $active != 100 ]
	do
		sleep 1
		active=$(ping -c 1 "$ip" | grep -Po "[0-9]+(?=%)" )
	done
	notify-send  "Server" "Server has been shutdown"
	echo "Server has been shutdown"
}

shutdown_server
check_server_shutdown
exit 0
