#!/bin/sh

key=$(cat "$HOME"/.scripts/.env/mac-address-proxmox-server)
wol "$key"

ip=$(cat "$HOME"/.scripts/.env/ip-proxmox-server)
active=$(ping -c 1 "$ip" | grep -Po "[0-9]+(?=%)" )

notify-send  "Server" "Starting Server"
while [ $active != 0 ]
do
	sleep 1
	active=$(ping -c 1 "$ip" | grep -Po "[0-9]+(?=%)" )
done

echo "Server has started"
notify-send  "Server" "Server has started"
