#!/bin/sh
BROWSER=$1
URL=$2

case "$BROWSER" in
	brave) brave --profile-directory="Profile 1" $URL;;
	thorium) thorium-browser --profile-directory="Profile 1" $URL;;
	qutebrowser) qutebrowser --basedir ~/eureciclo/qutebrowser/ $URL;;
	*) brave --profile-directory="Profile 1" $1;;
esac
