#!/bin/sh
BROWSER=$1
URL=$2

case "$BROWSER" in
	brave) brave --profile-directory=Default $URL;;
	thorium) thorium-browser --profile-directory="Profile 4" $URL;;
	qutebrowser) qutebrowser $URL;;
	chromium) chromium --profile-directory="Profile 0" $URL ;;
	helium) helium-browser --profile-directory="Profile 1" $URL ;;
	*) qutebrowser $1;;
esac
