#!/bin/sh
BROWSER=$1
URL=$2

case "$BROWSER" in
	brave) brave --profile-directory="Profile 3" --window-name="call" --app=https://meet.google.com ;;
	thorium) thorium-browser --window-name="call" --app=https://meet.google.com $URL;;
	qutebrowser) qutebrowser --basedir /home/frank/eureciclo/web-call --qt-arg name call;;
	*) thorium-browser --window-name="call" --app=https://meet.google.com $URL;;
esac
