#!/bin/sh
BROWSER=$1

case "$BROWSER" in
	brave) brave --profile-directory="Profile 3" ;;
	thorium) thorium-browser --profile-directory="Profile 5" ;;
	*) brave --profile-directory="Profile 3" ;;
esac
