#!/bin/sh
BROWSER=$1

case "$BROWSER" in
	brave) brave --profile-directory=Default ;;
	thorium) thorium-browser --profile-directory="Profile 4" ;;
	qutebrowser) qutebrowser ;;
	*) qutebrowser ;;
esac
