#!/bin/sh
BROWSER=$1
URL=$2
WINDOW_NAME="uberall"

case "$BROWSER" in
	brave) brave --profile-directory="Profile 3" --window-name=$WINDOW_NAME --app=$URL ;;
	thorium) thorium-browser --window-name=$WINDOW_NAME --app=$URL ;;
	zen) zen-browser ;;
	chromium) chromium --profile-directory="Default" --window-name=$WINDOW_NAME --app=$URL ;;
	*) chromium --profile-directory="Default" --window-name=$WINDOW_NAME --app=$URL ;;
esac
