#!/bin/sh
BROWSER=$1

case "$BROWSER" in
	brave) brave --profile-directory="Profile 1" ;;
	thorium) thorium-browser --profile-directory="Profile 1" ;;
	qutebrowser) qutebrowser --basedir ~/eureciclo/qutebrowser/ ;;
	*) brave --profile-directory="Profile 1" ;;
esac
