#!/bin/sh
BROWSER=$1
URL="https://meet.google.com"
WINDOW_NAME="call"

case "$BROWSER" in
	brave) brave --profile-directory="Profile 3" --window-name=$WINDOW_NAME --app=$URL ;;
	thorium) thorium-browser --window-name=$WINDOW_NAME --app=$URL ;;
	chromium) chromium --profile-directory="Default" --window-name=$WINDOW_NAME --app=$URL ;;
	helium) helium-browser --window-name=$WINDOW_NAME --profile-directory="Default" --app=$URL ;;
	*) ${BROWSER:-helium-browser} --window-name=$WINDOW_NAME --profile-directory="Default" --app=$URL ;;
esac
