#!/bin/sh

connect_to_vm() {
	echo "Connecting to the VM"
	notify-send "windows-server"  "Connecting to the VM"
	sleep 4
	remmina $HOME/.local/share/remmina/group_rdp_eureciclo-windows-vm_eureciclo-windows-vm-corgi-walleye-ts-net.remmina
}

start-server
start-vm.sh 103 windows-server
connect_to_vm
exit 0
