#!/bin/sh
ip=$(cat $HOME/.scripts/.env/ip-proxmox-server)
active=$(ping -c 1 "$ip" | grep -Po "[0-9]+(?=%)" )
pass=$(cat $HOME/.scripts/.env/ssh | grep -Po '(?<=ssh-password=).*')

# Checks if server is up if not starts it
start_server() {
	echo "Checking if the server is up"
	notify-send "windows-server" "Checking if the server is up"
	if [ $active -eq 100 ]; then
		/usr/bin/dash $HOME/.scripts/start-server
	else
		echo "Server already up"
		notify-send "windows-server" "Server already up"
	fi
}

start_vm() {
	status=$(sshpass -p $pass ssh -i ~/.ssh/personal_id_ed25519_2023-05 proxmox qm status 103 | grep -Eo 'running|stopped')
	case $status in
		"stopped")
			echo "Starting the VM"
			notify-send "windows-server"  "Starting the VM"
			sshpass -p $pass ssh -i ~/.ssh/personal_id_ed25519_2023-05 proxmox qm start 103 &&
			echo "VM Started"
			notify-send "windows-server"  "VM Started"
			;;
		"running")
			echo "VM Already Started"
			notify-send "windows-server"  "VM Already Started"
			;;
	esac
}

connect_to_vm() {
	echo "Connecting to the VM"
	notify-send "windows-server"  "Connecting to the VM"
	sleep 4
	remmina $HOME/.local/share/remmina/group_rdp_eureciclo-windows-vm_192-168-1-122.remmina
}

start_server
start_vm
connect_to_vm
exit 0
