#!/bin/sh

slack &
/usr/bin/dash $HOME/.scripts/brave-eureciclo &
/usr/bin/dash $HOME/.scripts/brave-call &
/usr/bin/dash $HOME/.scripts/brave-videos &
spotify-launcher &

# sleep 10

# for i in $(seq 6 7)
# do
# 		if [ $(xrandr --query | grep -c HDMI) = 1 ]; then
# 				xdotool key super+period && xdotool key super+$i && xdotool key super+period && xdotool key super+$i key shift+super+period
# 		fi
# done
