#!/bin/sh

/usr/bin/dash $HOME/.scripts/show_keybinds.sh &
/usr/bin/dash $HOME/.scripts/work-tmux &
/usr/bin/pritunl-client-electron &
/usr/bin/dash $HOME/.scripts/google-chat &
/usr/bin/dash $HOME/.scripts/web-eureciclo &
/usr/bin/dash $HOME/.scripts/vpn-conectar &
/usr/bin/dash $HOME/.scripts/web-call &
# /usr/bin/dash $HOME/.scripts/web-videos &
/usr/bin/dash $HOME/.scripts/web-pessoal &
spotify-launcher &
kill-xautolock.sh &
