#!/bin/sh

/usr/bin/dash $HOME/.scripts/show_keybinds.sh &
/usr/bin/dash $HOME/.scripts/work-tmux &
slack &
/usr/bin/pritunl-client-electron &
/usr/bin/dash $HOME/.scripts/web-eureciclo &
zen-browser -P 'Google Chat' &
/usr/bin/dash $HOME/.scripts/vpn-conectar &
/usr/bin/dash $HOME/.scripts/web-call &
# /usr/bin/dash $HOME/.scripts/web-videos &
/usr/bin/dash $HOME/.scripts/web-pessoal &
spotify-launcher &
