#!/bin/sh

# Start each program only if not already running (idempotent).
run_if_not_running() {
	pattern=$1
	shift
	if ! pgrep -f "$pattern" >/dev/null 2>&1; then
		"$@" &
	fi
}

run_if_not_running "web-call" /usr/bin/dash "$HOME/.scripts/web-call"
run_if_not_running "tmuxp load.*work" /usr/bin/dash "$HOME/.scripts/work-tmux"
run_if_not_running "web-uberall" /usr/bin/dash "$HOME/.scripts/web-uberall"
# run_if_not_running "databricks" /usr/bin/dash $HOME/.scripts/databricks
run_if_not_running "web-pessoal" /usr/bin/dash "$HOME/.scripts/web-pessoal"
/usr/bin/bash "$HOME/.scripts/configure-trackball.sh" &
run_if_not_running "slack" /usr/bin/slack
run_if_not_running "awsvpnclient" "$HOME/.local/bin/awsvpnclient"
run_if_not_running "datagrip" datagrip
# cursor &
# 1password &
# spotify-launcher &
# /usr/bin/drawio &
noisetorch -i  alsa_input.usb-C-Media_Electronics_Inc._USB_Advanced_Audio_Device-00.iec958-stereo &
rm $HOME/Downloads

#################
# DISABLED
#################
# dbeaver &
# /usr/bin/dash $HOME/.scripts/show_keybinds.sh &
# /usr/bin/dash $HOME/.scripts/web-videos &
