#!/bin/sh

st -t notas -e tmux new -s notas &
st -t diversos -e tmux new -s diversos &
st -t database -e tmux new -s database &
slack &
obsidian &
spotify &
dbeaver &
/usr/bin/dash /usr/local/bin/brave-eureciclo &
/usr/bin/dash /usr/local/bin/brave-pessoal &
/usr/bin/dash /usr/local/bin/windows
