#!/bin/sh

st -t notas -e tmux new -s notas &
st -t diversos -e tmux new -s diversos &
st -t database -e tmux new -s database &
slack &
obsidian &
spotify &
dbeaver &
brave --profile-directory="Profile 1" &
brave --profile-directory=Default &



